apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: {{ template "guestbook.name" . }}-guestbookweb
    chart: {{ template "guestbook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "guestbook.name" . }}-guestbookweb
    release: {{ .Release.Name }}
  ports:
  - port: 80
    targetPort: 9080

---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: {{ template "guestbook.name" . }}-guestbookdb
    chart: {{ template "guestbook.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    app: {{ template "guestbook.name" . }}-guestbookdb
    release: {{ .Release.Name }}
  ports:
  - port: 3306
    targetPort: 3306
